### ISSUE TITLE
paru --clean doesn't work

### ISSUE THREAD

**Issue by starquake** [Morganamilo/paru#10]
`paru -c` works but `paru --clean` doesn't.

The response I get is: `error: invalid option '--clean'` which is a pacman response.

I tried looking in the code and stepping through the code but I have a hard time following what's going on. Probably because I'm still quite new to Rust.

If you want I can try to fix it and create a PR if you can give me some hints.

**Comment by Morganamilo** [comment]
Thanks for finding.

Seems as you're interested in making a PR I'll explain the issue the best I can

https://github.com/Morganamilo/paru/blob/27d45df64fdb257849deb415ea08d56cba9d9964/src/main.rs#L186


Here all of the pacman arguments we used are capture. So when you add do `paru -c` it passes that `-c` to the `pacman -R` command which works. However using `paru --clean` causes it to call `pacman -R --clean` which is not a valid pacman command.

This could be fixed by using `pacman_globals()` instead of `pacman_args()`. However I like the fact that it passes the extra flags along so that in theory you could do `paru -c --nosave` to pass `--nosave` to the remove command.

For that case, you'd just want to call `args.remove('c') args.remove("clean")` after the above line.

**Comment by starquake** [comment]
Well that was fun.

args.remove(char) was not implemented so I used a string. Let me know if this is okay or if you want me to implement it.

**Comment by NICHOLAS85** [comment]
It seems this is broken on my end. using `paru -c/--clean` gives an error message:
`error: no targets specified (use -h for help)`

**Comment by NICHOLAS85** [comment]
It seems this is broken on my machine. Using `paru -c/--clean` results in an error message:
`error: no targets specified (use -h for help)`

Specifying `-c/--clean` twice works however

**Comment by Morganamilo** [comment]
Yeah looks like when there's nothing to remove paru just calls `pacman -R` and then pacman spits that error. So it works but the error is just misleading. Anyway fixed now.

**Comment by NICHOLAS85** [comment]
> Yeah looks like when there's nothing to remove paru just calls pacman -R and then pacman spits that error. So it works but the error is just misleading. Anyway fixed now.
Ahh, that would make sense. And thanks for the quick fix.
