### ISSUE TITLE
build fails in alpm.rs

### ISSUE THREAD

**Issue by zeule** [Morganamilo/paru#1215]
### Affected Version

https://aur.archlinux.org/paru.git at 7008763e43b8f950394acf736abd5dc0179d3ff1

### Description
Building fails with the current PKGBUILD and rustc 1.79.0 (129f3b996 2024-06-10) (Arch Linux rust 1:1.79.0-1)

### Output
```
error[E0308]: mismatched types
   --> /home/eugene/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/src/cb.rs:244:60
    |
244 |         unsafe { alpm_option_set_logcb(self.as_ptr(), Some(cb), &*ctx as *const _ as *mut _) };
    |                                                       ---- ^^ expected fn pointer, found fn item
    |                                                       |
    |                                                       arguments to this enum variant are incorrect
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, _, *mut __va_list_tag)`
                  found fn item `extern "C" fn(_, _, _, [__va_list_tag; 1]) {logcb::<LogCbImpl<T, F>>}`
help: the type constructed contains `extern "C" fn(*mut c_void, u32, *const u8, [__va_list_tag; 1]) {logcb::<LogCbImpl<T, F>>}` due to the type of the argument passed
   --> /home/eugene/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/src/cb.rs:244:55
    |
244 |         unsafe { alpm_option_set_logcb(self.as_ptr(), Some(cb), &*ctx as *const _ as *mut _) };
    |                                                       ^^^^^--^
    |                                                            |
    |                                                            this argument influences the type of `Some`
note: tuple variant defined here
   --> /build/rust/src/rustc-1.79.0-src/library/core/src/option.rs:579:5
```

**Comment by lestofante** [comment]
can confirm with rust 1.81 too.

I also get a warning:
`warning: Patch `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)` was not used in the crate graph.
Patch `aur-depends v3.0.0 (https://github.com/Morganamilo/aur-depends?rev=30c2c1#30c2c150)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.`

This seems because ALPM is version 4.0.0.
Changin the Carrgo.toml to from alpm ={ "4.0.0"} to alpm ={ version="4.0.0", features = [ "generate" ] }  and build with makepkg -e (-e is to avoid override the change in the source folder), seems to work
