### ISSUE TITLE
Display PKGBUILD for packages from chaotic-aur

### ISSUE THREAD

**Issue by Cuteistfox** [Morganamilo/paru#1217]
Chaotic-AUR is a project that builds aur packages. They only check pkgbuilds when it gets added or is broken. If a package get hijacked, chaotic still auto-updates. It will be usefull to have a option to display PKGBUILDs for packages built and put in chaotic-aur like how it is in normal aur.
**Have you checked the readme and man page for this feature?**
Yes
**Have you checked previous issues for this feature?**
Yes

**Comment by Morganamilo** [comment]
This actually can be done by adding the chaotic-aur as a custom repo in paru.conf.

```
[chaotic-aur]
Url = https://github.com/chaotic-aur/packages
```

```
morganamilo@starlight master ~git/paru % paru -Ss paru-git
  aur/paru-git 2.0.3.rebuild.1.r0.g5355012-1 [+47 ~5.34]
      Feature packed AUR helper
  chaotic-aur/paru-git 2.0.3.rebuild.1.r0.g5355012-1
      Feature packed AUR helper

morganamilo@starlight master ~git/paru % paru -Gp chaotic-aur/paru-git | head
  # Maintainer: Morgan <morganamilo@archlinux.org>
  pkgname=paru-git
  _pkgname=paru
  pkgver=2.0.3.rebuild.1.r0.g5355012
  pkgrel=1
  pkgdesc='Feature packed AUR helper'
  url='https://github.com/morganamilo/paru'
  source=("git+https://github.com/morganamilo/paru")
  backup=("etc/paru.conf")
  arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64')
```

Though it sounds like what you really want is some sort of pkgbuild review step before installing binary packages from chaotic-aur. That will never happen because it would require paru to integrate specifically with chaotic. And even then as you're installing binaries you can't actually prove the PKGBUILD you're looking at built the binary you're about to install.
