### ISSUE TITLE
package openvino is installed again and again -> latest-commit

### ISSUE THREAD

**Issue by boesi** [Morganamilo/paru#1233]
### Affected Version
```
$ paru -V
paru v2.0.3 - libalpm v14.0.0
```
### Description
paru wants to install the package openvino again and again for some time now.
```
$ paru
 endeavouros is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
1 devel/openvino      2024.3.0-1    -> latest-commit
:: Packages to exclude (eg: 1 2 3, 1-3):
:: ^C⏎
```
```
$ paru -Qi
Name                     : openvino
Version                  : 2024.3.0-1
[...]
```
```
$ paru -Si
Name                     : openvino
Version                  : 2024.3.0-1
```
If I build and the openvino myself, latest-commit is gone.
```
$ paru -Rsdd openvino
$ git clone https://aur.archlinux.org/openvino.git
$ cd openvino
$ makepkg
$ paru -S --asdeps <all packages makepkg complains about>
$ makepkg
$ sudo pacman -U --asdeps openvino-<version>-x86_64.pkg.tar.zst
```
But with the next update of openvino latest-commit is back.

So what's wrong on my system? Openvino is the only package with this problem.

Btw. yay also behaves  like this, but at the moment I only have paru installed.

**Comment by urbenlegend** [comment]
I am also seeing this with the `sunshine` package. Reinstalling it will very briefly stop the update notice, but later on it will show up again even though the PKGBUILD hasn't been updated in a month. I also see it going from version -> latest-commit, which seems strange to me.

This also happened recently. I felt like there was a few weeks where it did not bug me, but within the past few days I've been seeing sunshine pop up repeatedly and I am unsure as to the root cause.

**Comment by Morganamilo** [comment]
openvino and sunshine both appear to be big repos that get constant commits. -git packages track the head of their git repo so even though the pkgbuild has not changed, you get a newer package after any commit to the upstream git repo.

If you don't want this, disable Devel or add them to IgnoreDevel in paru.conf
