### ISSUE TITLE
error: failed to run custom build command for `alpm v4.0.1`

### ISSUE THREAD

**Issue by guixianren2** [Morganamilo/paru#1250]
**Encountered a problem, unable to install, please tell me how to solve it**

Caused by:
  process didn't exit successfully: `/home/guxin/.cache/yay/paru/src/paru-2.0.4/target/release/build/alpm-4dea8ea09155ec51/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/guxin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Bie401** [comment]
Facing the same issue, I am trying to install paru by following the below commands.

`sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si`

Error logs:

`error: failed to run custom build command for `alpm v4.0.1`

Caused by:
  process didn't exit successfully: `/home/prithvi/AUR_repo/paru/src/paru-2.0.4/target/release/build/alpm-c86ec86fd681e05a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/prithvi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by Maherilaza** [comment]
You can try installing directly with cargo
`cargo install --git https://github.com/Morganamilo/paru.git`

**Comment by BishopWolf** [comment]
trying directly with cargo i get
```
error: failed to run custom build command for `alpm v4.0.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installvw5Zco/release/build/alpm-9c141fe3a5ca0c82/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `paru v2.0.4 (https://github.com/Morganamilo/paru.git#9177d820)`, intermediate artifacts can be found at `/tmp/cargo-installvw5Zco`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by BishopWolf** [comment]
If your system is not yet updated (like Manjaro), then use
```
cargo install --git https://github.com/Morganamilo/paru.git --tag v2.0.2
```

**Comment by jmakov** [comment]
> If your system is not yet updated (like Manjaro), then use
> 
> ```
> cargo install --git https://github.com/Morganamilo/paru.git --tag v2.0.3
> ```

On Manjaro, didn't work for me. The error remains.

**Comment by geeflaxx** [comment]
we should wait

**Comment by jmakov** [comment]
Thank you for the tip. But breaking things 1x/month is not for me, back to Ubuntu.

**Comment by q210520993** [comment]
I had the same issue as you, but I solved it with "sudo cargo install --git https://github.com/Morganamilo/paru.git".
Must have 'sudo'

**Comment by BishopWolf** [comment]
Manjaro has upgraded pacman, so paru its back running

**Comment by nixpulvis** [comment]
I'm on arch. Updating my mirrorlist and rebuilding seems to have fixed the issue for me.
