### ISSUE TITLE
Package vlang is always detected to update

### ISSUE THREAD

**Issue by sunng87** [Morganamilo/paru#135]
After installed [vlang](https://aur.archlinux.org/packages/vlang) via paru, it's now detected as an update every time I run `paru` although there is no change with version number. It doesn't happen with `yay` so I think it's a `paru` issue.

**Comment by Morganamilo** [comment]
Wrong is a devel package due to it pulling one patch from a git repo. Paru will end up updating the package when that git repo updates.

They should depend on a specific commit or just put the patch in the air repo.

Yay would do the same. Just you probably never installed the package with yay so yay doesn't track it.

**Comment by sunng87** [comment]
I see. Thanks for clarify.
