### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by guihkx** [Morganamilo/paru#150]
Hello, are there any plans to support other languages in paru? Thanks!

**Comment by crapStone** [comment]
@Morganamilo what do you think about that: https://lib.rs/crates/fluent-bundle

**Comment by Morganamilo** [comment]
I have no idea, I've not looked at localisation libs and when I do I won't be able to get a proper opinion until I play with them a bit.

**Comment by crapStone** [comment]
Should I implement it for some files and you can decide if you want it?

**Comment by Morganamilo** [comment]
Can do. One of my requirements is auto generating templates like .po files.

**Comment by crapStone** [comment]
[Fluent](https://www.projectfluent.org/) is a very new project (the first specification was released in 2019) that aims to provide the best translation possible for each language. But because it is such a young project the ecosystem and especially the Rust implementation isn't very mature yet (the Rust implementation is very low-level and doesn't even support the full specification).

Imho this project is a great new approach to make translations and we could benefit greatly by using it. But because it is still so new there will be probably more than one rewrite of the translation system necessary if we want to use the newest features.

If you don't want this i will use the tried and proven [GNU gettext](https://lib.rs/crates/tr).

**Comment by alerque** [comment]
Even though the ecosystem and library ergonomics are still playing catch up a little bit, Fluent brings *so* much to the table not offered by previous generations of translation systems that I think it's by far the best way to go for a project like this.

I've built several CLI's with Fluent based l10n, if/when work gets started on this I'd be willing to help a little.
