### ISSUE TITLE
packages to exclude when upgrading AUR packages

### ISSUE THREAD

**Issue by wi18b088** [Morganamilo/paru#177]
yay used to present the user with the option to exclude certain available upgrades from the AUR. It looked like this:

==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)

This is very handy when there are unfixed installation problems with packages and compilation will take for ages. paru on the other hand will just ask for review and then for installation without the option to exclude packages.

:: Proceed to review? [Y/n]:

:: Proceed with installation? [Y/n]:

I would love to see that feature in some future release.

**Comment by Morganamilo** [comment]
--upgrademenu same as yay

**Comment by wi18b088** [comment]
Thank you, exactly what I was looking for!

**Comment by she3o** [comment]
Hi, can you make this the default behavior, or at least add it to readme. People coming from `yay` expect it to work that way (which is better imho) and they would think `paru` is missing a feature.
I think defaulting to this behavior is better because there are packages (like `v8-r`) that take forever to upgrade and get upgrades every few hours. I would normally upgrade AUR packages every week or so. and upgrade `v8-r` every couple of months.

**Comment by Morganamilo** [comment]
Readme mention is fine, defaults not changing though.

**Comment by wi18b088** [comment]
> Hi, can you make this the default behavior, or at least add it to readme. People coming from `yay` expect it to work that way (which is better imho) and they would think `paru` is missing a feature.
> I think defaulting to this behavior is better because there are packages (like `v8-r`) that take forever to upgrade and get upgrades every few hours. I would normally upgrade AUR packages every week or so. and upgrade `v8-r` every couple of months.

You could shadow the `paru` command with a custom bash function in your `.bashrc`:

```bash
paru(){
	if [ $# -eq 0 ]; 
	then
		command paru -Syu --upgrademenu
	elif [ $1 = "-Sua" ]; 
	then
		command paru -Sua --upgrademenu
	else
		command paru "$@"
	fi
}

```

**Comment by Morganamilo** [comment]
...or uncomment edit menu in paru.conf
