### ISSUE TITLE
Need an option to rebuild reverse dependencies of a target package to avoid function break.

### ISSUE THREAD

**Issue by enihcam** [Morganamilo/paru#287]
scenario:
A custom linux kernel upgrade triggers rebuild of all its out-of-tree modules.

**Comment by Morganamilo** [comment]
Shouldn't out of tree modules use dkms and avoid this issue?

**Comment by enihcam** [comment]
> Shouldn't out of tree modules use dkms and avoid this issue?

i think dkms is a workaround to this specific scenario. what about glibc and its reverse dependencies in AUR? i mean there still can be many cases to be benefited from rebuild automation, right? :)

**Comment by Morganamilo** [comment]
For the general case you could probably just pipe `pactree -r` into paru.

**Comment by enihcam** [comment]
> For the general case you could probably just pipe `pactree -r` into paru.

I know, but the reason i request this feature is that i sometimes forget building the reverse dependencies before i reboot my headless remote devices. i need a flag or an option in config file to automate this.

**Comment by trevorgunn** [comment]
This is a complicated problem which I think is best handled manually. First, not all library updates require rebuilds. Second, even when they do require rebuilds it might not be for every package. For instance a python library will need to be rebuilt if python gets a major version bump but a python script will not. Third, not all AUR maintainers handle this the same way, some will bump the pkgrel but some will not and whether paru does or does not bump the pkgrel you will then have mismatched versions. Also, sometimes I don't want to rebuild a package because the compilation is long/tedious/requires older versions of devel tools that I don't want to figure out so it's easier for me to just edit the binary with a hex editor so that it points to the newer library.

And you're just never going to be able to automate all of that complexity without maintaining a ton of rules for each AUR package and each library.

**Comment by Morganamilo** [comment]
Exactly. Too complex and therefore out of scope.
