### ISSUE TITLE
Paru opening with vi when $EDITOR=nano

### ISSUE THREAD

**Issue by erikdubois** [Morganamilo/paru#320]
Can we add the editor to the .config/paru/paru.conf file?
So we can be sure it is going to be that one?
I have not seen a switch to set it either.

Is this possible?

Name            : paru-bin
Version         : 1.5.0-1
Arch Linux

**Comment by Morganamilo** [comment]
Paru does not use an editor.

**Comment by trevorgunn** [comment]
Paru uses a pager (less) which shares some keybindings with vi, if that's what you are referring to.

If you don't like having to press `q` to exit, you can `-e / --quit-at-eof` to your less flags (`export LESS="e"` in bashrc/zshrc). You might also want to add `-F / --quit-if-one-screen` and/or `-X` which doesn't clear the text after less exits (`LESS="eFX"`).

Alternatively, you can set the `Pager` to `/usr/bin/cat` in paru.conf:
```ini
...
#
# Binary OPTIONS
#
[bin]
...
Pager=/usr/bin/cat
```

**Comment by erikdubois** [comment]
I would suggest to do that by default
gives a nice professional result
![cat](https://user-images.githubusercontent.com/10594806/114600866-20d7b600-9c95-11eb-9798-1cd7895a2441.png)
If the user sees something he does not like - he can go and edit it and still gives him the control to check the pkgbuild

**Comment by erikdubois** [comment]
As a side note

someone suggested 'bat' as package alternative to cat.
it was still on there
although there is this error I must say I like the coloring of the syntax
![bat](https://user-images.githubusercontent.com/10594806/114601144-76ac5e00-9c95-11eb-9b2f-e35f386b027b.png)

**Comment by erikdubois** [comment]
Now I did change the config of aurvote to reflect Pager=/usr/bin/bat
nice indeed
![bat](https://user-images.githubusercontent.com/10594806/114601419-c559f800-9c95-11eb-8a9b-24692527a94d.png)

**Comment by trevorgunn** [comment]
Paru will run the output through `bat`  if it detects it (but with the `--plain` flag to disable `bat`'s line numbers/pager) and then feed it to the pager. If you set the pager to `/usr/bin/bat` then it's technically running `bat` twice. `bat` also uses less as a pager if what it is displaying is more than one screen (i.e. the less flag `-F / --quit-if-one-screen` that I talked about).

`/usr/bin/cat` is not the default because you might need to review several pkgbuilds and .install scripts and whatnot and that might fill up 10 screens worth, so a pager is justified in the general case. Again, there are flags you can pass to less to make it friendlier.

Paru uses the flags `SRX` by default, you can add more by exporting, for instance, `LESS="eFSRX"`.
