### ISSUE TITLE
paru binary contains referenct to $srcdir

### ISSUE THREAD

**Issue by marcstraube** [Morganamilo/paru#336]
### Affected Version
`paru -V`: 1.5.1

### Description
**Have you checked previous issues for this bug?** yes; none found

### Output
When building the paru package, makepkg shows the following warning:

```sh
WARNING: Package contains reference to $srcdir
```

Grepping through the $pkgdir, it shows that the paru binary contains the reference to the $srcdir.

**Comment by trevorgunn** [comment]
Which Rust toolchain are you compiling with?

**Comment by Morganamilo** [comment]
The debug symbols contain filepaths. There's not anything to be done on paru's side.

**Comment by marcstraube** [comment]
I've used the default rust toolchain.
I know that the warning is nothing serious, but I thought I might inform you nonetheless.

**Comment by SandaruKasa** [comment]
This is an upstream issue with Rust as a whole, and is a real pain for reproducible builds.

It can be somewhat comabtted by using [`--remap-path-prefix`](https://github.com/rust-lang/rust/issues/41555), but even Arch's in-repo packages do not do it. Take, for example, [tokei](https://gitlab.archlinux.org/archlinux/packaging/packages/tokei/-/blob/main/PKGBUILD). If you use that PKGBUILD, you will get the same warning from `makepkg`.

Anyways, what I am trying to say is that there is no reason to keep this issue open here, because it's a problem of either Arch or Rust as a whole, and, for now, there is not anything that `paru` has to do to address this.

**Comment by Morganamilo** [comment]
It's open because I did want to tackle it. I opened https://github.com/rust-lang/cargo/pull/9407 ages ago but didn't have the time to continue with it. If I find the time I'd like to get it finished.
