### ISSUE TITLE
When getting a new MKPKG can we also get the name of who made it?

### ISSUE THREAD

**Issue by c2oc** [Morganamilo/paru#339]

**Comment by trevorgunn** [comment]
I don't follow. Can you elaborate?

**Comment by c2oc** [comment]
Yeah, sorry. I'm not sure if it's even possible but it'd be cool to have the latest mkpkg author's username printed just before the review process. It could also allow some interesting features, like skipping (automatically or with the usual format [y/n/s]) if the old mkpkg is released by the same author.

**Comment by trevorgunn** [comment]
They're called PKGBUILDs. Makepkg is something else (a script packaged with pacman).

Paru shows git diffs by default on updated PKGBUILDs but I forget how much information is included in those diffs and I don't have time to check right now (I believe it shows the commit author though).

**Comment by c2oc** [comment]
>  (I believe it shows the commit author though).

If it does then I hope the feature I proposed will get added

> They're called PKGBUILDs. Makepkg is something else (a script packaged with pacman).

Aye, thanks for pointing it out!

**Comment by Morganamilo** [comment]
The git diffs do not contain the author. I'm not interested in this feature in general. However when it comes to security I am very against it.

The git author can easily be faked so that's out. RPC metadata is okay but maybe a bit racy.

I don't really believe in trusting an author because they make one fine package anyway.

Plus when I look at a pkgbuild I'm usually more worried about error than malice.
