### ISSUE TITLE
paru repeatedly shows libadwaita-shortwave-1:r1937.afee036-1 as upgradable

### ISSUE THREAD

**Issue by mabod** [Morganamilo/paru#422]
### Affected Version
**paru v1.7.2 - libalpm v13.0.0**

### Description
paru repeatedly shows libadwaita-shortwave-1:r1937.afee036-1
as upgradable although it is already installed:

```
9# pacman -Q | grep   libadwaita-shortwave
libadwaita-shortwave 1:r1937.afee036-1
```

```
10# paru -Syyu
:: Synchronizing package databases...
 core                                                   133,6 KiB  1553 KiB/s 00:00 [------------------------------------------------] 100%
 extra                                                 1566,9 KiB  5,86 MiB/s 00:00 [------------------------------------------------] 100%
 community                                                5,6 MiB  14,2 MiB/s 00:00 [------------------------------------------------] 100%
 multilib                                               149,6 KiB  1543 KiB/s 00:00 [------------------------------------------------] 100%
 endeavouros                                             17,3 KiB  75,8 KiB/s 00:00 [------------------------------------------------] 100%
 liquorix                                                 2,7 KiB  8,73 KiB/s 00:00 [------------------------------------------------] 100%
:: Starting full system upgrade...
warning: linux-zen: local (5.12.13.zen1-1) is newer than extra (5.12.12.zen1-1)
warning: linux-zen-headers: local (5.12.13.zen1-1) is newer than extra (5.12.12.zen1-1)
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
warning: opencl-amd: ignoring package upgrade (20.50.1234664-5 => 21.10.1247438-1)
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: Marked out of date: rate-arch-mirrors  teamviewer
:: Orphans: rate-arch-mirrors

Aur (1) libadwaita-shortwave-1:r1937.afee036-1

:: Proceed to review? [Y/n]: n
```
yay is not doing that:

```
11# yay -Syyu
:: Synchronizing package databases...
 core                                                   133,6 KiB  1182 KiB/s 00:00 [------------------------------------------------] 100%
 extra                                                 1566,9 KiB  6,99 MiB/s 00:00 [------------------------------------------------] 100%
 community                                                5,6 MiB  10,8 MiB/s 00:01 [------------------------------------------------] 100%
 multilib                                               149,6 KiB  1360 KiB/s 00:00 [------------------------------------------------] 100%
 endeavouros                                             17,3 KiB  91,9 KiB/s 00:00 [------------------------------------------------] 100%
 liquorix                                                 2,7 KiB  9,06 KiB/s 00:00 [------------------------------------------------] 100%
:: Starting full system upgrade...
warning: linux-zen: local (5.12.13.zen1-1) is newer than extra (5.12.12.zen1-1)
warning: linux-zen-headers: local (5.12.13.zen1-1) is newer than extra (5.12.12.zen1-1)
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> linux-zen: local (5.12.13.zen1-1) is newer than extra (5.12.12.zen1-1)
 -> linux-zen-headers: local (5.12.13.zen1-1) is newer than extra (5.12.12.zen1-1)
 -> opencl-amd: ignoring package upgrade (20.50.1234664-5 => 21.10.1247438-1)
 -> libpdfium-nojs: local (4472.r0.f3ad7d9dd2-1) is newer than AUR (4389.r1.157601b9b9-1)
 -> Orphaned AUR Packages:  rate-arch-mirrors
 -> Flagged Out Of Date AUR Packages:  rate-arch-mirrors  teamviewer
 there is nothing to do
```

The corresponding PKGBUILD is this:
```

19# cat PKGBUILD 
# Maintainer: Alex Dewar <alex.dewar@gmx.co.uk>
# Contributor: Pellegrino Prevete <pellegrinoprevete@gmail.com>
# Contributor: Philip Goto <philip.goto@gmail.com>
# Contributor: Davide Depau <davide@depau.eu>
# Contributor: Rafael Fontenelle <rafaelff@gnome.org>
# Contributor: Marco Melorio <marco.melorio@protonmail.com>
# Contributor: Bakasura <bakasura@protonmail.ch>

_pkgname=libadwaita
pkgname=$_pkgname-shortwave
pkgver=r1937.afee036
_commit=9a52895fcd5a906791606400db1028fa0e527854
pkgrel=1
epoch=1
pkgdesc="Library full of GTK widgets for mobile phones (version required by shortwave)"
url="https://gitlab.gnome.org/GNOME/$_pkgname"
license=(LGPL)
arch=(i686 x86_64 armv7h aarch64)
depends=(gtk4)
makedepends=(git gobject-introspection meson sassc vala wayland-protocols)
source=("git+$url")
provides=($_pkgname)
conflicts=($_pkgname)
md5sums=(SKIP)

prepare() {
    git -C $_pkgname checkout $_commit
}

build() {
    arch-meson $_pkgname build -Dgtk_doc=false -Dexamples=true
    DESTDIR="$pkgdir" ninja -C build
}

package() {
    DESTDIR="$pkgdir" ninja -C build install
}
```

**Comment by Morganamilo** [comment]
What's the contents of `~/.cache/paru/devel.json`?

**Comment by Morganamilo** [comment]
Oh wait I see pkgbuild is wrong to source the latest version then checkout an earlier version in prepare.

Source should be `source=("git+$url#commit=$_commit")` and prepare removed.

**Comment by mabod** [comment]
The same issue occurs with package `libpdfium-nojs-4389.r1.157601b9b9-1` with PKGBUILD:

```
8# cat PKGBUILD 
# Maintainer: Felix Kauselmann <licorn@gmail.com>

pkgname=libpdfium-nojs
pkgver=4472.r0.f3ad7d9dd2
pkgrel=1
pkgdesc="Open-source PDF rendering engine."
arch=('x86_64')
url="https://pdfium.googlesource.com/pdfium/"
license=('BSD')
depends=('freetype2' 'lcms2' 'libjpeg' 'openjpeg2' 'icu')
conflicts=('libpdfium-bin')
provides=('libpdfium')
makedepends=('git' 'python2' 'gn' 'ninja')

source=("git+https://pdfium.googlesource.com/pdfium"
    "git+https://chromium.googlesource.com/chromium/src/build.git"
    "libpdfium.pc"
    )

md5sums=('SKIP'
    'SKIP'
    'feb270967925a0844b1b9a9e15288eb3'
    )

pkgver() {

  cd $srcdir/pdfium

  # Version = branch name/number + number of commits since branch creation
  # + short head
  printf  "%s.r%s.%s" $(git rev-parse --abbrev-ref HEAD | cut -d '/' -f2)\
   $(git rev-list --count master..) $(git rev-parse --short HEAD)

}

prepare() {

  cd "$srcdir/pdfium"

  ln -sf $srcdir/build build

  # Pdfium is developed alongside Chromium and does not provide releases
  # Upstream recommends using Chromium's dev channels instead

  # Extract pdfium branch name used in stable channel from omahaproxy and do
  # a checkout
  git checkout "chromium/$(curl https://omahaproxy.appspot.com/linux?channel=stable | cut -d'.' -f 3)"

  # git checkout "chromium/$(curl https://omahaproxy.appspot.com/linux?channel=beta | cut -d'.' -f 3)"
  # git checkout "chromium/$(curl https://omahaproxy.appspot.com/linux?channel=dev | cut -d'.' -f 3)"

  # Extract build repo revision needed from DEPS file and do a checkout
  cd "$srcdir/pdfium/build"
  git checkout $(awk '/build_revision/ {print substr($2,2,40)}' $srcdir/pdfium/DEPS) -q
  
  # Use system provided icu library (unbundling)
  mkdir -p "$srcdir/pdfium/third_party/icu"
  ln -sf "$srcdir/build/linux/unbundle/icu.gn" "$srcdir/pdfium/third_party/icu/BUILD.gn"

  # Download and decode shim header script needed to unbundle icu (gittiles is weird)
  mkdir -p "$srcdir/pdfium/tools/generate_shim_headers/"
  echo "Downloading generate_shim_headers script from Chromium."
  curl https://chromium.googlesource.com/chromium/src/+/master/tools/generate_shim_headers/generate_shim_headers.py?format=TEXT \
    | base64 --decode > "$srcdir/pdfium/tools/generate_shim_headers/generate_shim_headers.py"
  echo "Done."
  
  # Create fake gclient_args.gni file to satisfy include list for build/config/compiler/compiler.gni
  touch "$srcdir/build/config/gclient_args.gni"
  
} 

build() {

  cd "$srcdir/pdfium"

  local _flags=(
      'is_clang=false'
      'use_sysroot=false'
      'is_debug=false'
      'symbol_level=0'
      'pdf_enable_v8=false'
      'pdf_enable_xfa=false'
      'treat_warnings_as_errors=false'
      'use_system_libjpeg=true'
      'use_system_zlib=true'
      'pdf_bundle_freetype=false'
      'use_system_freetype=true'
      'use_system_lcms2=true'
      'use_system_libpng=true'
      'use_custom_libcxx=false'
      'pdf_is_standalone = true'
      'use_system_libopenjpeg2 = true'
      'is_component_build = true'
      'use_gold = false' 
  )
  
  gn gen out/Release --script-executable=/usr/bin/python2 --args="${_flags[*]}"
  ninja -C out/Release pdfium

  # set pdfium version in pc file
  sed "s/@VERSION@/${pkgver}/g" -i "${srcdir}/libpdfium.pc"

}

package() {

  cd "$srcdir/pdfium"

  install -D -m644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
  install -D public/*.h --target-directory="${pkgdir}/usr/include/pdfium"
  install -D public/cpp/* --target-directory="${pkgdir}/usr/include/pdfium/cpp"
  install -D docs/* --target-directory="${pkgdir}/usr/share/doc/pdfium"
  install -Dm755 out/Release/libpdfium.so --target-directory="${pkgdir}/usr/lib"
  install -Dm644 ${srcdir}/libpdfium.pc --target-directory=${pkgdir}/usr/lib/pkgconfig

}
```
And again, this does not happen with yay.

**Comment by Morganamilo** [comment]
I already told you what the issue was. Also I assume the issue does not happen on yay because you've not told yay to track the package.

**Comment by mabod** [comment]
Ok.  Bare with me. Please be patient. 
How would I tell yay to track the package so that I get the same behaviour as with paru?
On the other hand, how do I tell paru not to track that package?

**Comment by Morganamilo** [comment]
Yay and paru both have the exact same handling of -git packages. Which they think libadwaita-shortwave is because of the unversioned source.

When yay/paru installs a git package they note the current commit hash in ~/.cache/yay/vcs.json or ~/.cache/paru/devel.json respectively. When a new commit it pushed then yay/paru can see the different hash and prompt to update.

So the way to trigger it is install package with the helper, then wait for a new commit, then attempt to upgrade with that helper.

You can avoid that by turning of devel updates. But then all devel packages go unchecked.

**Comment by alexdewar** [comment]
@Morganamilo I'm the package maintainer for libadwaita-shortwave. I've updated the PKGBUILD as you suggested, but I still feel like maybe paru could be modified to better distinguish VCS from non-VCS pacakges.

How about a heuristic based on package names? If the package name ends in ``-git``, ``-svn``, ``-vcs`` and (possibly) ``-devel`` then you could apply the logic of checking for new upstream commits and otherwise not. This would also fix the case for ``pdfium`` (discussed above) where it's not clear how the PKGBUILD could be modified to appease paru.

**Comment by Morganamilo** [comment]
Generally a non vcs package using a vcs source will specify a specific tag or commit fragment (see PKGBUILD(5)) so I don't see an issue with the current approach.

pdfium should imo define the commits in the pkgbuild instead of dynamically fetching the version. It is meant to be a stable software after all.

Though I can't say if there's a rule for that though.

**Comment by alexdewar** [comment]
Either way you're essentially using a heuristic, *however* the VCS packaging guidelines *do* state that packages not requiring a specific commit should have the appropriate suffix on the ``pkgname``: https://wiki.archlinux.org/title/VCS_package_guidelines

A PKGBUILD that checks out a specific git commit in its ``prepare()`` function isn't doing anything wrong according to the Arch packaging guideless, but if it is just using whatever the current upstream commit in ``master`` is and it *doesn't* have a ``-git`` suffix in its ``pkgname`` then it *is* wrong.

So I feel like this is the right rule: i.e.
``is_package_vcs = vcs_in_source_array() && has_vcs_suffix()``

**Comment by Morganamilo** [comment]
https://wiki.archlinux.org/title/VCS_package_guidelines#Guidelines

The wiki says:

> Suffix pkgname with -cvs, -svn, -hg, -darcs, -bzr, -git etc. unless the package fetches a specific release.

So libpdfium-nojs should have a suffix given it does not specify a specific release.

Also it's correct for paru to treat it as a devel package because a new commit could lead to a new pkgver.

**Comment by alexdewar** [comment]
That's true! Ok, bad example... So it really should have a suffix.

My point is that other non-VCS packages are totally at liberty to checkout whatever commit they want in ``prepare()`` and it's a bug for paru to assume that the commit in the upstream master branch is the one the PKGBUILD wants.

**Comment by Morganamilo** [comment]
Is it correct though? If you know the commit ahead of time in should be specified in the source URL.

Yes it works if you use prepare but that's probably bad practise. And I don't cater to pkgbuilds using bad practise.

**Comment by selmf** [comment]
@Morganamilo I am the package maintainer for libpdfium-nojs and I can assure you that there are technical reasons for the git checkout approach taken in the build process and these include the requirement to keep a copy of the main branch around, even if the package will build from a different branch.

I am in fact not too stupid to use a git tag or git fragment in a PKGBUILD and I'd more than happily use them for libpdfium-nojs if I could. Sadly, the build and development practices and the total lack of a proper release from upstream require me to assemble the sources for a stable build by non-standard means, which include the requirement to compare the current stable branch (which is a moving target, not a single branch!) with the main branch in order to obtain a correct version number.

For paru/yay this is problematic because you assume that every package using vcs sources will always target the latest commit on the main branch.

As for the question if this approach is correct or acceptable I can assure you while it evidently irritates some people who don't take the time to fully understand the PKGBUILD and the technical reasons it operates the way it does, it was in fact inspected and deemed acceptable as part of a reject deletion request on the aur-request mailing list.

Now for the way forward I perfectly agree with you that you are in fact in no way obliged to cater to PKGBUILDs who don't fit the standard template and you probably agree with me that PKGBUILD maintainers are not obliged to cater to assumptions AUR helpers make.

This however still leaves us with the problem that paru/yay users seem to experience unnecessary rebuilds when using libpdfium-nojs due to our incompatible versioning mechanisms and we get complaints about this. To resolve this issue, I could either add a warning that clearly indicates that the package is incompatible with some AUR helpers and should be added to an ignore list or we could try to find a better heuristic so paru/yay can more reliably detect edge cases like this.

Please let me know what you'd prefer.

**Comment by Morganamilo** [comment]
> which include the requirement to compare the current stable branch (which is a moving target, not a single branch!) with the main branch in order to obtain a correct version number.

I don't get why you have to try and obtain a version number for a stable package. Can't you just hardcore the version and commit hashes like a stable package normally would?
