### ISSUE TITLE
[Feature request] Support automatically finding file sources

### ISSUE THREAD

**Issue by coolreader18** [Morganamilo/paru#615]
(as far as I can tell this hasn't been brought up before)

The main place aur helpers can't be used (or, well, yay/paru, I haven't used others so I'm not sure if there's prior art for this) is when the aur package has a `file://` source, e.g. [`ttf-ms-win10`](https://aur.archlinux.org/packages/ttf-ms-win10). It'd be cool if one could put all the `.ttf`s in `~/.config/paru/filesources/ttf-ms-win10/` (bikesheddable) and they'd get hardlinked/symlinked/copied into the build directory. I'm going to look into working on this, but let me know if this seems desirable.

**Comment by Morganamilo** [comment]
That may actually be a good feature request for makepkg instead. Not sure if there's one already open.

**Comment by FabioLolix** [comment]
Those source has to be user provided, aur helpers works after you put it alongside the pkgbuild, is possible to configure a common source destination SRCDEST= in `/etc/makepkg.conf` (or copy it to ~/.makepkg.conf) but that is for all sources

Personally I'm using that since years as I'm building packages that share the same sources and I'm revisioning and contacting other packagers to make work their with common srcdest=
