### ISSUE TITLE
freeipa-client | unable to satisfy dependencies

### ISSUE THREAD

**Issue by MarcelWalk** [Morganamilo/paru#778]
### Affected Version
paru v1.10.0 - libalpm v13.0.1

### Description
Cant install package `freeipa-client`
Same issue as here https://github.com/Jguer/yay/issues/1631

### Output
See attached file

```sh
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg
```
[paru.log](https://github.com/Morganamilo/paru/files/8960386/paru.log)

**Comment by Morganamilo** [comment]
So basically paru (and yay) does what I will now coin pkgbase promotion. Paru (and yay's) model of installing packages is to build a pkgbase and then install all wanted pkgnames in the pkgbase.

So when paru pulls in a package that has already had a package of the same pkgbuild resolved. It will slot the new package next to the packages from the existing pkgbase. 

This generally works perfectly because a pkgbases tend to share all its dependencies. However an individual package can declare its own unique dependencies, these being only required at runtime.

A solution to this would be to either smartly also slot the runtime deps of the package above the pkgbase it's promoted to. Or don't do pkgbuild promotion but still ensure to build once.
