### ISSUE TITLE
paru: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xfzv** [Morganamilo/paru#880]
After updating `openssl` from 1.1.1.q-1 to 3.0.7-2 (testing repo), I'm getting the following error when running any `paru` command:

```
paru: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory)
```

**Comment by obj-obj** [comment]
@ssleert any rebuild fixes it, I just rebuilt the `1.11.1` release to fix it

**Comment by Nalsai** [comment]
I was using the [release build](https://github.com/Morganamilo/paru/releases/tag/v1.11.1), which now doesn't work anymore due to this issue.

**Comment by Alsan** [comment]
I have the same exact problem after system upgrade. Then I install openssl-1.1 solved the problem.

ps: I'm using a variant of archlinux.

**Comment by zeertzjq** [comment]
Just re-running `makepkg -si` in the cloned directory with `PKGBUILD` (likely `~/.cache/paru/clone/paru/`) fixes this. I think this is just how AUR packages work.

**Comment by Piqlet** [comment]
> I have the same exact problem after system upgrade. Then I install openssl-1.1 solved the problem.
> 
> ps: I'm using a variant of archlinux.

me too fixed
```
sudo pacman -S openssl-1.1
```

**Comment by linnabraham** [comment]
> > I have the same exact problem after system upgrade. Then I install openssl-1.1 solved the problem.
> > ps: I'm using a variant of archlinux.
> 
> me too fixed
> 
> ```
> sudo pacman -S openssl-1.1
> ```

I'snt openssl 3.0.7 the latest version? Is this the recommended way then?

**Comment by ouuan** [comment]
Although rebuilding `paru`/`paru-git` or installing `openssl-1.1` can fix this, I think we need a rebuild of `paru-bin` or a new release of paru.

**Comment by GlenMerlin** [comment]
> I'snt openssl 3.0.7 the latest version? Is this the recommended way then?
It is the latest version but 1.1.1 is still supported until mid 2023 I believe. Only a few distros have jumped up to the 3.0 (for some reason there was no 2.0 version)

1.1.1 is not affected by the critical vulnerability that 3.0.0-3.0.6 is so this is currently a safe thing to do.

**Comment by m0xsec** [comment]
> try to build paru-git pkg)

Following up to confirm that cloning `paru-git` from the AUR and running `makepkg -si` fixes the issue. If you previously had a different pre-built paru package installed, you will need to remove it as it will be in conflict with the `paru-git` package.

imo this is a better solution than installing a dated version of OpenSSL.

**Comment by Alsan** [comment]
I've check that multiple version of OpenSSL can be installed simultaneously, I have 3.0.7, 1.1.1.s-2, 1.0.2.u-1 installed in my system. The 1.0 is required by the WPS (an office suite application), 1.1 doesn't have any required by listed (and I don't have this version before this issue), the 3.0 is required by other packages required by the core. Therefore, 3.0 is the default in the system, and it could be a safe but might not be the recommended way to solve this issue.

I just wondering why paru is looking for the older version without a recompile.

**Comment by justinkb** [comment]
it's "looking for the older version" because it linked to libssl.so.1.1 and libcrypto.so.1.1 during build. it is a runtime dependency established at build time

**Comment by stevenxxiu** [comment]
Installing `paru-git` isn't required. Installing `paru` is good enough by itself.

**Comment by eclairevoyant** [comment]
this is not a bug with paru.... if you use AUR packages that depend on a library then you need to rebuild those packages.

**Comment by eclairevoyant** [comment]
If there's an issue with `paru-bin`, flag that package out of date. Also, the owner of this repo is a TU, I'm sure they're aware.
If you knew this then why did you file the issue?

**Comment by mmirus** [comment]
@xfzv thanks for filling this issue! It was helpful for me as a user trying to understand what the problem is and how to navigate it.

**Comment by eclairevoyant** [comment]
@mmirus the aurweb comments already explain this, btw

**Comment by mmirus** [comment]
I could be misunderstanding you, but if you mean the comments at https://aur.archlinux.org/packages/paru, they link to this issue. Either way, the information in this issue was helpful to me as a supplement to information I found elsewhere.

**Comment by eclairevoyant** [comment]
> If you actually do that yourself, please stop. You shouldn't flag AUR packages out-of-date to report bugs

In this case, `paru-bin` is built against OpenSSL 1.1, which means that the PKGBUILD **in the AUR** is broken and should be fixed to point to `openssl-1.1` instead of just `openssl` - that is a packaging problem and not an upstream problem, so flagging the AUR package is an absolutely correct action here.

> `paru-bin` is now broken and re-building it won't make any difference, the package will have to be updated

Incorrect, see above.

> As you can see, it helps some users

> Edit: And it helps [some reddit users](https://old.reddit.com/r/archlinux/comments/yn5o8a/paru_is_broken_after_update_error_while_loading/) too.

Users' inability to read comments elsewhere isn't a reason to file a GitHub issue; issues are meant for developers to make changes to their code or documentation.

The original issue you filed lacked any sort of details and just contained an error message - generally not a good sign of a well-written issue. `paru` has no issues and no code needs to be changed here - this repo is written in Rust anyway, not C, so expecting a Rust codebase to change anything after a C library updates doesn't make sense unless there are direct calls to said lib.
If your concern was specifically about `paru-bin`, you missed mentioning that when opening the issue. But again, as above, that is a packaging concern.

> Someone would have opened a similar issue anyway

I hope not. Filing an issue with upstream about a downstream packaging issue doesn't make sense.

**Comment by VicoHBB** [comment]
I wanna ask if these error message is related with this issue or should I create another one?
```bash
paru: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by ouuan** [comment]
> In this case, `paru-bin` is built against OpenSSL 1.1, which means that the PKGBUILD **in the AUR** is broken and should be fixed to point to `openssl-1.1` instead of just `openssl` - that is a packaging problem and not an upstream problem, so flagging the AUR package is an absolutely correct action here.

I believe the "shouldn't flag AUR packages out-of-date to report bugs" doesn't mean opening an issue on GitHub instead. It means AUR comments for AUR packages and Bug Reports for repo packages. Flagging as out of date means a new release has come out, which is not for a breaking dependency.

> Filing an issue with upstream about a downstream packaging issue doesn't make sense.

Usually, it is better to comment under the AUR package. But all the AUR packages of paru are maintained by Morganamilo, so I don't think this is a big problem.

This time, it is a big breaking issue affecting many users, so opening this issue here will definitely help many users. This doesn't mean opening an issue for all small packaging issues in the future.

> If you personally use `paru-bin`, you can edit the PKGBUILD on your own system and rebuild, that **will** fix it.

Installing `openssl-1.1` is just a workaround, not a fix. We need the upstream to rebuild the binary to actually fix it.

BTW, installing `openssl-1.1` doesn't require editing the PKGBUILD or rebuilding. Just install it.

**Comment by xmawja** [comment]
**[just rebuild the repo and you good to go](https://github.com/Morganamilo/paru#readme)**

`sudo pacman -S --needed base-devel`

`git clone https://aur.archlinux.org/paru.git`

`cd paru`

`makepkg -si`

**Comment by enihcam** [comment]
i really hope in the end this discussion can lead to a feature request that `paru` helps detecting dependency changes that affect AUR packages, and rebuilds them.

**Comment by eclairevoyant** [comment]
@enihcam Already asked for in #287, it's out of scope for this.

**Comment by GerardoGR** [comment]
I also got impact by this. I guess the next step is to update the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru) to use the `1.11.2` version. Are there any plans for that?

**Comment by Morganamilo** [comment]
No because 1.11.2 was only released as a binary rebuild and the paru aur packages is source based.

**Comment by Serede** [comment]
I have `paru-bin-1.11.2-1-aarch64` installed and I'm still facing this issue. Am I missing anything?

**Comment by Morganamilo** [comment]
So, the binaries are built in a docker container that I don't have much control of. I guess when I built 1.11.2 the arm one hadn't switched to the new openssl yet. Just use the non-bin one for now.

**Comment by chrishoage** [comment]
I am also hitting this with `paru-v1.11.2-armv7h.tar.zst`. Building paru on a Raspberry Pi 3 is painfully slow. 

It's been nearly a year is there any chance of a re-rebuild with the updated libssl symbols?
