### ISSUE TITLE
[Feature Request] Drop asp and use devtools-git-poc instead

### ISSUE THREAD

**Issue by zhanghua000** [Morganamilo/paru#992]
**Have you checked the readme and man page for this feature?** Yes
**Have you checked previous issues for this feature?** Yes
According to [this](https://archlinux.org/news/git-migration-announcement/) news, asp will stop working after upstream finishes migrating job. They recommend using `pkgctl repo clone` instead.

**Comment by memchr** [comment]
The git migration has been [completed](https://archlinux.org/news/git-migration-completed/) as of UTC 2023-05-21 and `asp` has been deprecated. It's possible that svn2git will soon stop working.

---

Since the packages are now accessible at https://gitlab.archlinux.org/archlinux/packaging/packages, is it feasible to clone/download them directly from there instead of relying on `pkgctl`, which requires numerous dependencies due to its `devtools` package?

**Comment by zhanghua000** [comment]
As pkgctl is not only a source downloader like asp, but also an unified interface for devtools, it also has the ability to create chroot environment and build package in that clean environment, I think we should depend on it more instead clone source directly.

**Comment by memchr** [comment]
Thanks for bringing up that point. I understand that `devtools` has advanced features beyond just downloading the source, but as you can see here, paru currently only uses `asp` to [fetch](https://github.com/Morganamilo/paru/blob/257e01155501e3f93ed218f3853156a030b20c58/src/download.rs#L226) or [display](https://github.com/Morganamilo/paru/blob/257e01155501e3f93ed218f3853156a030b20c58/src/download.rs#L571) PKGBUILDs from the repo. So relying on `pkgctl` more may not be of much benefit, and it may be more convenient to fetch PKGBUILDs directly from Arch's GitLab instance.

**Comment by justinkb** [comment]
imo, every paru user should be using chroot building anyway, which requires devtools already

**Comment by mabod** [comment]
Is this topic moving? paru still fetches outdated package files.
E.g. `paru -G linux-lts` fetches package version 6.1.29
